version: '3.8'

services:
  host:
    image: eluki/peer-meeting
    environment:
      - "Coturn:Enabled=true"
      - "Coturn:TurnAddress=[coturnIP]:3478"
      - "Coturn:SharedSecret=VerySecretSharedKey"
    ports:
     - target: 80
       published: 30005
       protocol: tcp
       mode: host
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      placement:
        max_replicas_per_node: 1
    logging:
      driver: "json-file"
      options:
        max-size: "3m"
        max-file: "3"

  coturn:
    image: coturn/coturn
    command: 
      - "-n"
      - "--log-file=stdout"
      - "--listening-port=3478"
      - "--min-port=49160"
      - "--max-port=49200"
      - "--external-ip='$(detect-external-ip)'"
      - "--realm='$(hostname)'"
      - "--use-auth-secret"
      - "--static-auth-secret=VerySecretSharedKey"
      - "--no-tls"
      - "--no-tcp"
      #- "--no-stun" #optional disable stun functionality
    networks:
      - outside
    deploy:
      replicas: 1
    logging:
      driver: "json-file"
      options:
        max-size: "3m"
        max-file: "3"

networks:
  outside:
    external: true
    name: "host"